#!/usr/bin/env bash

set -e

mysql -uquiron -pquiron -D quirondb <<EOF
ALTER TABLE PERSON_USERS ALTER COLUMN PersonTypeID SET DEFAULT 3;

ALTER TABLE USERS_ROLES DROP FOREIGN KEY fk_ROLES_has_USERS_ROLES1;
ALTER TABLE USERS_ROLES
ADD CONSTRAINT fk_ROLES_has_USERS_ROLES1
FOREIGN KEY (RoleID) REFERENCES ROLES (RoleID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE USERS_ROLES DROP FOREIGN KEY fk_ROLES_has_USERS_USERS1;
ALTER TABLE USERS_ROLES
ADD CONSTRAINT fk_ROLES_has_USERS_USERS1
FOREIGN KEY (UserID) REFERENCES USERS (UserID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PERSON_USERS DROP FOREIGN KEY fk_USERS_has_PERSONS_USERS1;
ALTER TABLE PERSON_USERS
ADD CONSTRAINT fk_USERS_has_PERSONS_USERS1
FOREIGN KEY (UserID) REFERENCES USERS (UserID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PATIENTS DROP FOREIGN KEY fk_PATIENTS_PERSONS1;
ALTER TABLE PATIENTS
ADD CONSTRAINT fk_PATIENTS_PERSONS1
FOREIGN KEY (PatientID) REFERENCES PERSONS (PersonID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE PERSON_USERS DROP FOREIGN KEY fk_PERSON_USERS_PERSONS1;
ALTER TABLE PERSON_USERS
ADD CONSTRAINT fk_PERSON_USERS_PERSONS1
FOREIGN KEY (PersonID, PersonTypeID) REFERENCES PERSONS (PersonID, PersonTypeID) ON DELETE CASCADE ON UPDATE CASCADE;

EOF