#!/usr/bin/env bash

set -e

mysql -uquiron -pquiron -D quirondb <<EOF

-- MySQL Script generated by MySQL Workbench
-- Sat Nov 24 19:14:33 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema quirondb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS quirondb ;

-- -----------------------------------------------------
-- Schema quirondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS quirondb DEFAULT CHARACTER SET utf8 ;
USE quirondb ;

-- -----------------------------------------------------
-- Table ENTITIES
-- -----------------------------------------------------
DROP TABLE IF EXISTS ENTITIES ;

CREATE TABLE IF NOT EXISTS ENTITIES (
  EntityID INT NOT NULL AUTO_INCREMENT,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  PRIMARY KEY (EntityID))
ENGINE = InnoDB
COMMENT = 'Source of the ID that connects providers and patients with address and contact information.';


-- -----------------------------------------------------
-- Table PERSON_TYPES
-- -----------------------------------------------------
DROP TABLE IF EXISTS PERSON_TYPES ;

CREATE TABLE IF NOT EXISTS PERSON_TYPES (
  PersonTypeID INT NOT NULL AUTO_INCREMENT,
  PersonTypeName NVARCHAR(45) NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  ModifiedDate DATETIME NULL COMMENT 'Date and time the record was last updated.',
  PRIMARY KEY (PersonTypeID))
ENGINE = InnoDB
COMMENT = 'Type of a person.';


-- -----------------------------------------------------
-- Table PERSONS
-- -----------------------------------------------------
DROP TABLE IF EXISTS PERSONS ;

CREATE TABLE IF NOT EXISTS PERSONS (
  PersonID INT NOT NULL,
  PersonTypeID INT NOT NULL,
  Title NVARCHAR(8) NULL COMMENT 'A courtesy title. For example, Mr. or Ms.',
  FirstName NVARCHAR(45) NOT NULL COMMENT 'First name of the person.',
  MiddleName NVARCHAR(45) NULL COMMENT 'Middle name or middle initial of the person.',
  LastName NVARCHAR(45) NOT NULL COMMENT 'Last name of the person.',
  LastName2 NVARCHAR(45) NULL COMMENT 'Second Last name of the person (If Any).',
  Suffix NVARCHAR(10) NULL COMMENT 'Surname suffix. For example, Sr. or Jr.',
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  ModifiedDate DATETIME NULL COMMENT 'Date and time the record was last updated.',
  PRIMARY KEY (PersonID),
  CONSTRAINT fk_PERSONS_ENTITIES
    FOREIGN KEY (PersonID)
    REFERENCES ENTITIES (EntityID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_PERSONS_PERSON_TYPES1
    FOREIGN KEY (PersonTypeID)
    REFERENCES PERSON_TYPES (PersonTypeID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Human beings involved with Quiron Project patients, patients contacts, and providers.';

CREATE INDEX fk_PERSONS_ENTITIES_idx ON PERSONS (PersonID ASC);

CREATE INDEX fk_PERSONS_PERSON_TYPES1_idx ON PERSONS (PersonTypeID ASC);

CREATE UNIQUE INDEX PERSONS_pk ON PERSONS (PersonID ASC, PersonTypeID ASC);


-- -----------------------------------------------------
-- Table PROVIDERS
-- -----------------------------------------------------
DROP TABLE IF EXISTS PROVIDERS ;

CREATE TABLE IF NOT EXISTS PROVIDERS (
  ProviderID INT NOT NULL,
  NPI NVARCHAR(45) NOT NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (ProviderID),
  CONSTRAINT fk_PROVIDERS_PERSONS1
    FOREIGN KEY (ProviderID)
    REFERENCES PERSONS (PersonID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_PROVIDERS_PERSONS1_idx ON PROVIDERS (ProviderID ASC);


-- -----------------------------------------------------
-- Table ORGANIZATION_TYPES
-- -----------------------------------------------------
DROP TABLE IF EXISTS ORGANIZATION_TYPES ;

CREATE TABLE IF NOT EXISTS ORGANIZATION_TYPES (
  OrganizationTypeID INT NOT NULL AUTO_INCREMENT,
  Name NVARCHAR(45) NOT NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (OrganizationTypeID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table ORGANIZATIONS
-- -----------------------------------------------------
DROP TABLE IF EXISTS ORGANIZATIONS ;

CREATE TABLE IF NOT EXISTS ORGANIZATIONS (
  OrganizationID INT NOT NULL,
  OrganizationTypeID INT NOT NULL,
  Name NVARCHAR(45) NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (OrganizationID),
  CONSTRAINT fk_ORGANIZATIONS_ENTITIES1
    FOREIGN KEY (OrganizationID)
    REFERENCES ENTITIES (EntityID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_ORGANIZATIONS_ORGANIZATION_TYPES1
    FOREIGN KEY (OrganizationTypeID)
    REFERENCES ORGANIZATION_TYPES (OrganizationTypeID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_ORGANIZATIONS_ORGANIZATION_TYPES1_idx ON ORGANIZATIONS (OrganizationTypeID ASC);


-- -----------------------------------------------------
-- Table PATIENTS
-- -----------------------------------------------------
DROP TABLE IF EXISTS PATIENTS ;

CREATE TABLE IF NOT EXISTS PATIENTS (
  PatientID INT NOT NULL,
  BirthDate DATE NULL,
  Gender NVARCHAR(1) NULL,
  CompanyID INT NULL,
  SubscriberCode NVARCHAR(25) NULL,
  IsPrimarySubscriber BIT NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (PatientID),
  CONSTRAINT fk_PATIENTS_PERSONS1
    FOREIGN KEY (PatientID)
    REFERENCES PERSONS (PersonID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_PATIENTS_ORGANIZATIONS1
    FOREIGN KEY (CompanyID)
    REFERENCES ORGANIZATIONS (OrganizationID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_PATIENTS_ORGANIZATIONS1_idx ON PATIENTS (CompanyID ASC);


-- -----------------------------------------------------
-- Table SERVICES
-- -----------------------------------------------------
DROP TABLE IF EXISTS SERVICES ;

CREATE TABLE IF NOT EXISTS SERVICES (
  Name VARCHAR(45) NOT NULL,
  ServiceID INT NOT NULL AUTO_INCREMENT,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (ServiceID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table COUNTRIES
-- -----------------------------------------------------
DROP TABLE IF EXISTS COUNTRIES ;

CREATE TABLE IF NOT EXISTS COUNTRIES (
  CountryID INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key for countries.',
  CountryCode NVARCHAR(3) NOT NULL COMMENT 'ISO standard code for countries.',
  Name NVARCHAR(45) NOT NULL COMMENT 'Country name.',
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was Created.',
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (CountryID))
ENGINE = InnoDB
COMMENT = 'Lookup table containing the ISO standard codes for countries.';

CREATE UNIQUE INDEX CountryCode_UNIQUE ON COUNTRIES (CountryCode ASC);


-- -----------------------------------------------------
-- Table STATE_PROVINCES
-- -----------------------------------------------------
DROP TABLE IF EXISTS STATE_PROVINCES ;

CREATE TABLE IF NOT EXISTS STATE_PROVINCES (
  StateProvinceID INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key for State_Provinces records.',
  StateProvinceCode NVARCHAR(3) NOT NULL COMMENT 'ISO standard state or province code.',
  Name NVARCHAR(45) NOT NULL COMMENT 'State or province description.',
  CountryID INT NOT NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  ModifiedDate DATETIME NULL COMMENT 'Date and time the record was last updated.',
  PRIMARY KEY (StateProvinceID),
  CONSTRAINT fk_STATE_PROVINCES_COUNTRIES1
    FOREIGN KEY (CountryID)
    REFERENCES COUNTRIES (CountryID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'State and province lookup table.';

CREATE INDEX fk_STATE_PROVINCES_COUNTRIES1_idx ON STATE_PROVINCES (CountryID ASC);


-- -----------------------------------------------------
-- Table ADDRESS_TYPES
-- -----------------------------------------------------
DROP TABLE IF EXISTS ADDRESS_TYPES ;

CREATE TABLE IF NOT EXISTS ADDRESS_TYPES (
  AddressTypeID INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key for Address_Type records.',
  Name NVARCHAR(45) NOT NULL COMMENT 'Address type description. For example, Billing, Home, or Shipping.',
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  ModifiedDate DATETIME NULL COMMENT 'Date and time the record was last updated.',
  PRIMARY KEY (AddressTypeID))
ENGINE = InnoDB
COMMENT = 'Types of addresses stored in the Address table. ';


-- -----------------------------------------------------
-- Table ADDRESSES
-- -----------------------------------------------------
DROP TABLE IF EXISTS ADDRESSES ;

CREATE TABLE IF NOT EXISTS ADDRESSES (
  AddressID INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key for Address records.',
  AddressTypeID INT NOT NULL,
  AddressLine1 NVARCHAR(60) NOT NULL COMMENT 'First street address line.',
  AddressLine2 NVARCHAR(60) NULL COMMENT 'Second street address line.',
  City NVARCHAR(45) NOT NULL COMMENT 'Name of the city.',
  StateProvinceID INT NOT NULL COMMENT 'Unique identification number for the state or province. Foreign key to STATE_PROVINCES table.',
  PostalCode NVARCHAR(15) NOT NULL COMMENT 'Postal code for the street address.',
  Name NVARCHAR(45) NULL COMMENT 'It is mainly used to name the locations of branches of an organization.',
  Description NVARCHAR(45) NULL COMMENT 'It is mainly used to describe the locations of branches of an organization.',
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (AddressID),
  CONSTRAINT fk_ADDRESSES_STATE_PROVINCES1
    FOREIGN KEY (StateProvinceID)
    REFERENCES STATE_PROVINCES (StateProvinceID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ADDRESSES_ADDRESS_TYPES1
    FOREIGN KEY (AddressTypeID)
    REFERENCES ADDRESS_TYPES (AddressTypeID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Street address information for patiens, providers, care sites and pharmacies.';

CREATE INDEX fk_ADDRESSES_STATE_PROVINCES1_idx ON ADDRESSES (StateProvinceID ASC);

CREATE INDEX fk_ADDRESSES_ADDRESS_TYPES1_idx ON ADDRESSES (AddressTypeID ASC);


-- -----------------------------------------------------
-- Table ENTITY_ADDRESSES
-- -----------------------------------------------------
DROP TABLE IF EXISTS ENTITY_ADDRESSES ;

CREATE TABLE IF NOT EXISTS ENTITY_ADDRESSES (
  EntityID INT NOT NULL COMMENT 'Primary key. Foreign key to ENTITIES.EntityID.',
  AddressID INT NOT NULL COMMENT 'Primary key. Foreign key to ADDRESSES.AddressID.',
  CreatedDate DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  PRIMARY KEY (EntityID, AddressID),
  CONSTRAINT fk_ENTITIES_has_ADDRESSES_ENTITIES1
    FOREIGN KEY (EntityID)
    REFERENCES ENTITIES (EntityID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_ENTITIES_has_ADDRESSES_ADDRESSES1
    FOREIGN KEY (AddressID)
    REFERENCES ADDRESSES (AddressID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'Cross-reference table mapping patients, providers, and institutions to their addresses.';

CREATE INDEX fk_ENTITIES_has_ADDRESSES_ADDRESSES1_idx ON ENTITY_ADDRESSES (AddressID ASC);

CREATE INDEX fk_ENTITIES_has_ADDRESSES_ENTITIES1_idx ON ENTITY_ADDRESSES (EntityID ASC);


-- -----------------------------------------------------
-- Table SHIFTS
-- -----------------------------------------------------
DROP TABLE IF EXISTS SHIFTS ;

CREATE TABLE IF NOT EXISTS SHIFTS (
  ShiftID INT NOT NULL AUTO_INCREMENT COMMENT 'Work shift lookup table.',
  Name NVARCHAR(45) NOT NULL,
  Description NVARCHAR(512) NULL,
  StartDate DATE NULL,
  EndDate DATE NULL,
  Status CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'A=Active, D=Deleted',
  CreatedDate DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (ShiftID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table WEEK_DAYS
-- -----------------------------------------------------
DROP TABLE IF EXISTS WEEK_DAYS ;

CREATE TABLE IF NOT EXISTS WEEK_DAYS (
  WeekDayID INT NOT NULL AUTO_INCREMENT,
  WeekDayCode NCHAR(1) NOT NULL COMMENT 'M=Monday, T=Tuesday, W=Wednesday, R=Thursday, F=Friday, S=Saturday, U=Sunday',
  Name NVARCHAR(45) NOT NULL COMMENT 'Monday, Tuesday, Wednesday, Thursday, Friday, Saturday and Sunday',
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (WeekDayID))
ENGINE = InnoDB;

CREATE UNIQUE INDEX WeekDayCode_UNIQUE ON WEEK_DAYS (WeekDayCode ASC);


-- -----------------------------------------------------
-- Table SHIFTS_SCHEDULES
-- -----------------------------------------------------
DROP TABLE IF EXISTS SHIFTS_SCHEDULES ;

CREATE TABLE IF NOT EXISTS SHIFTS_SCHEDULES (
  ShiftID INT NOT NULL,
  WeekDayID INT NOT NULL,
  StartTime TIME NOT NULL,
  EndTime TIME NOT NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ShiftID, WeekDayID),
  CONSTRAINT fk_SHIFTS_SCHEDULES_SHIFTS1
    FOREIGN KEY (ShiftID)
    REFERENCES SHIFTS (ShiftID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_SHIFTS_SCHEDULES_WEEK_DAYS1
    FOREIGN KEY (WeekDayID)
    REFERENCES WEEK_DAYS (WeekDayID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_SHIFTS_SCHEDULES_WEEK_DAYS1_idx ON SHIFTS_SCHEDULES (WeekDayID ASC);


-- -----------------------------------------------------
-- Table PROVIDERS_SCHEDULES
-- -----------------------------------------------------
DROP TABLE IF EXISTS PROVIDERS_SCHEDULES ;

CREATE TABLE IF NOT EXISTS PROVIDERS_SCHEDULES (
  ProviderID INT NOT NULL,
  ShiftID INT NOT NULL,
  WeekDayID INT NOT NULL,
  OrganizationID INT NOT NULL,
  LocationID INT NOT NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID),
  CONSTRAINT fk_PROVIDERS_SCHEDULES_PROVIDERS1
    FOREIGN KEY (ProviderID)
    REFERENCES PROVIDERS (ProviderID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PROVIDERS_SCHEDULES_ENTITY_ADDRESSES1
    FOREIGN KEY (OrganizationID , LocationID)
    REFERENCES ENTITY_ADDRESSES (EntityID , AddressID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PROVIDERS_SCHEDULES_SHIFTS_SCHEDULES1
    FOREIGN KEY (ShiftID , WeekDayID)
    REFERENCES SHIFTS_SCHEDULES (ShiftID , WeekDayID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_PROVIDERS_SCHEDULES_ENTITY_ADDRESSES1_idx ON PROVIDERS_SCHEDULES (OrganizationID ASC, LocationID ASC);

CREATE INDEX fk_PROVIDERS_SCHEDULES_SHIFTS_SCHEDULES1_idx ON PROVIDERS_SCHEDULES (ShiftID ASC, WeekDayID ASC);


-- -----------------------------------------------------
-- Table VISITS
-- -----------------------------------------------------
DROP TABLE IF EXISTS VISITS ;

CREATE TABLE IF NOT EXISTS VISITS (
  VisitID INT NOT NULL AUTO_INCREMENT,
  PatientID INT NOT NULL,
  ProviderID INT NOT NULL,
  ShiftID INT NOT NULL,
  WeekDayID INT NOT NULL,
  OrganizationID INT NOT NULL,
  LocationID INT NOT NULL,
  ServiceID INT NOT NULL,
  Status NCHAR NOT NULL DEFAULT 'A' COMMENT 'A=Active, C=Completed, D=Deleted/Canceled',
  ScheduledStartDate DATETIME NULL,
  ScheduledEndDate DATETIME NULL,
  SymptomID INT NULL DEFAULT 0,
  SymptomName NVARCHAR(45) NULL DEFAULT 'Unknown',
  DiagnosticID INT NULL DEFAULT 0,
  DiagnosticName NVARCHAR(45) NULL DEFAULT 'Unknown',
  ActualStartDate DATETIME NULL,
  ActualEndDate DATETIME NULL,
  PatientBloodPressure DECIMAL(5,2) NULL DEFAULT 0,
  PatientWeight DECIMAL(5,2) NULL DEFAULT 0,
  PatientTemperature DECIMAL(5,2) NULL DEFAULT 0,
  PatientRespiration DECIMAL(5,2) NULL DEFAULT 0,
  PatientBMI DECIMAL(5,2) NULL DEFAULT 0,
  PatientHeight DECIMAL(5,2) NULL DEFAULT 0,
  PatientPulse DECIMAL(5,2) NULL DEFAULT 0,
  PatientSymptoms NVARCHAR(512) NULL,
  ProviderComments NVARCHAR(512) NULL,
  CreatedDate DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (VisitID),
  CONSTRAINT fk_VISITS_PATIENTS1
    FOREIGN KEY (PatientID)
    REFERENCES PATIENTS (PatientID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_VISITS_SERVICES1
    FOREIGN KEY (ServiceID)
    REFERENCES SERVICES (ServiceID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_VISITS_PROVIDERS_SCHEDULES1
    FOREIGN KEY (ProviderID , ShiftID , WeekDayID , OrganizationID , LocationID)
    REFERENCES PROVIDERS_SCHEDULES (ProviderID , ShiftID , WeekDayID , OrganizationID , LocationID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX fk_VISITS_PATIENTS1_idx ON VISITS (PatientID ASC);

CREATE INDEX fk_VISITS_SERVICES1_idx ON VISITS (ServiceID ASC);

CREATE INDEX fk_VISITS_PROVIDERS_SCHEDULES1_idx ON VISITS (ProviderID ASC, ShiftID ASC, WeekDayID ASC, OrganizationID ASC, LocationID ASC);


-- -----------------------------------------------------
-- Table TREATMENTS
-- -----------------------------------------------------
DROP TABLE IF EXISTS TREATMENTS ;

CREATE TABLE IF NOT EXISTS TREATMENTS (
  TreatmentID INT NOT NULL AUTO_INCREMENT,
  VisitID INT NOT NULL,
  StartDate DATETIME NULL,
  Enddate DATETIME NULL,
  PatientComments NVARCHAR(512) NULL,
  ProviderComments NVARCHAR(512) NULL,
  Status NCHAR(1) NULL DEFAULT 'A',
  Evaluation TINYINT NULL DEFAULT 0,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (TreatmentID),
  CONSTRAINT fk_TREATMENTS_VISITS1
    FOREIGN KEY (VisitID)
    REFERENCES VISITS (VisitID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX fk_TREATMENTS_VISITS1_idx ON TREATMENTS (VisitID ASC);


-- -----------------------------------------------------
-- Table USERS
-- -----------------------------------------------------
DROP TABLE IF EXISTS USERS ;

CREATE TABLE IF NOT EXISTS USERS (
  UserID INT NOT NULL AUTO_INCREMENT,
  Username NVARCHAR(16) NOT NULL,
  Email NVARCHAR(255) NULL,
  Password NVARCHAR(32) NOT NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (UserID));

CREATE UNIQUE INDEX Username_UNIQUE ON USERS (Username ASC);

CREATE UNIQUE INDEX Email_UNIQUE ON USERS (Email ASC);


-- -----------------------------------------------------
-- Table PHONE_TYPES
-- -----------------------------------------------------
DROP TABLE IF EXISTS PHONE_TYPES ;

CREATE TABLE IF NOT EXISTS PHONE_TYPES (
  PhoneTypeID INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key for telephone number type records.',
  Name NVARCHAR(45) NOT NULL COMMENT 'Name of the telephone number type',
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  ModifiedDate DATETIME NULL COMMENT 'Date and time the record was last updated.',
  PRIMARY KEY (PhoneTypeID))
ENGINE = InnoDB
COMMENT = 'Type of phone number of a person.';


-- -----------------------------------------------------
-- Table PERSON_PHONES
-- -----------------------------------------------------
DROP TABLE IF EXISTS PERSON_PHONES ;

CREATE TABLE IF NOT EXISTS PERSON_PHONES (
  PersonID INT NOT NULL COMMENT 'Entity identification number. Foreign key to PersonID.',
  Number NVARCHAR(25) NOT NULL COMMENT 'Telephone number identification number.',
  PhoneTypeID INT NOT NULL COMMENT 'Type of phone number. Foreign key to PhoneTypeID.',
  Extension NVARCHAR(10) NULL COMMENT 'Extension number.',
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  ModifiedDate DATETIME NULL COMMENT 'Date and time the record was last updated.',
  PRIMARY KEY (PersonID, Number, PhoneTypeID),
  CONSTRAINT fk_PERSON_PHONES_PERSONS1
    FOREIGN KEY (PersonID)
    REFERENCES PERSONS (PersonID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PERSON_PHONES_PHONE_TYPES1
    FOREIGN KEY (PhoneTypeID)
    REFERENCES PHONE_TYPES (PhoneTypeID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Telephone number and type of a person.';

CREATE INDEX fk_PERSON_PHONES_PERSONS1_idx ON PERSON_PHONES (PersonID ASC);

CREATE INDEX fk_PERSON_PHONES_PHONE_TYPES1_idx ON PERSON_PHONES (PhoneTypeID ASC);


-- -----------------------------------------------------
-- Table EMAIL_ADDRESSES
-- -----------------------------------------------------
DROP TABLE IF EXISTS EMAIL_ADDRESSES ;

CREATE TABLE IF NOT EXISTS EMAIL_ADDRESSES (
  EmailAddressID INT NOT NULL COMMENT 'Primary key. ID of this email address.',
  PersonID INT NOT NULL COMMENT 'Person associated with this email address.  Foreign key to PERSONS.PersonID',
  EmailAddress NVARCHAR(50) NOT NULL COMMENT 'E-mail address for the person.',
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  ModifiedDate DATETIME NULL COMMENT 'Date and time the record was last updated.',
  PRIMARY KEY (EmailAddressID),
  CONSTRAINT fk_EMAIL_ADDRESSES_PERSONS1
    FOREIGN KEY (PersonID)
    REFERENCES PERSONS (PersonID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Where to send a person email.';

CREATE INDEX fk_EMAIL_ADDRESSES_PERSONS1_idx ON EMAIL_ADDRESSES (PersonID ASC);


-- -----------------------------------------------------
-- Table CARD_TYPES
-- -----------------------------------------------------
DROP TABLE IF EXISTS CARD_TYPES ;

CREATE TABLE IF NOT EXISTS CARD_TYPES (
  CardTypeID INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key for credit card type records.',
  Name NVARCHAR(45) NOT NULL COMMENT 'Name of credit card type.',
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  PRIMARY KEY (CardTypeID))
ENGINE = InnoDB
COMMENT = 'Type or franchise of credit cards.';


-- -----------------------------------------------------
-- Table BANKS
-- -----------------------------------------------------
DROP TABLE IF EXISTS BANKS ;

CREATE TABLE IF NOT EXISTS BANKS (
  BankID INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key for Banks records.',
  Name NVARCHAR(45) NOT NULL COMMENT 'Name of the Bank.',
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (BankID))
ENGINE = InnoDB
COMMENT = 'Banks issuers of credit cards.';


-- -----------------------------------------------------
-- Table CREDITCARDS
-- -----------------------------------------------------
DROP TABLE IF EXISTS CREDITCARDS ;

CREATE TABLE IF NOT EXISTS CREDITCARDS (
  CreditCardID INT NOT NULL AUTO_INCREMENT COMMENT 'Primary key for CreditCard records.',
  PersonID INT NOT NULL,
  CardTypeID INT NULL COMMENT 'Credit card brand.',
  CardNumber NVARCHAR(25) NULL COMMENT 'Credit card number',
  BankID INT NULL COMMENT 'Credit card issuer bank.',
  ExpMonth TINYINT NULL COMMENT 'Credit card expiration month.',
  ExpYear SMALLINT NULL COMMENT 'Credit card expiration year.',
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date and time the record was created.',
  ModifiedDate DATETIME NULL COMMENT 'Date and time the record was last updated.',
  PRIMARY KEY (CreditCardID, PersonID),
  CONSTRAINT fk_PERSON_CREDITCARDS_PERSONS1
    FOREIGN KEY (PersonID)
    REFERENCES PERSONS (PersonID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PERSON_CREDITCARDS_CARD_TYPES1
    FOREIGN KEY (CardTypeID)
    REFERENCES CARD_TYPES (CardTypeID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PERSON_CREDITCARDS_BANKS1
    FOREIGN KEY (BankID)
    REFERENCES BANKS (BankID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Person credit card information.';

CREATE INDEX fk_PERSON_CREDITCARDS_PERSONS1_idx ON CREDITCARDS (PersonID ASC);

CREATE INDEX fk_PERSON_CREDITCARDS_CARD_TYPES1_idx ON CREDITCARDS (CardTypeID ASC);

CREATE INDEX fk_PERSON_CREDITCARDS_BANKS1_idx ON CREDITCARDS (BankID ASC);


-- -----------------------------------------------------
-- Table MEDICATIONS
-- -----------------------------------------------------
DROP TABLE IF EXISTS MEDICATIONS ;

CREATE TABLE IF NOT EXISTS MEDICATIONS (
  MedicationID INT NOT NULL AUTO_INCREMENT,
  Name NVARCHAR(45) NULL,
  CommonName NVARCHAR(45) NULL,
  Description NVARCHAR(512) NULL,
  GeneralInstructions NVARCHAR(512) NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (MedicationID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table PRESCRIPTIONS
-- -----------------------------------------------------
DROP TABLE IF EXISTS PRESCRIPTIONS ;

CREATE TABLE IF NOT EXISTS PRESCRIPTIONS (
  PrescriptionID INT NOT NULL AUTO_INCREMENT,
  MedicationID INT NULL,
  Instructions NVARCHAR(512) NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (PrescriptionID),
  CONSTRAINT fk_PRESCRIPTIONS_MEDICATIONS1
    FOREIGN KEY (MedicationID)
    REFERENCES MEDICATIONS (MedicationID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_PRESCRIPTIONS_MEDICATIONS1_idx ON PRESCRIPTIONS (MedicationID ASC);


-- -----------------------------------------------------
-- Table TREATMENTS_PRESCRIPTIONS
-- -----------------------------------------------------
DROP TABLE IF EXISTS TREATMENTS_PRESCRIPTIONS ;

CREATE TABLE IF NOT EXISTS TREATMENTS_PRESCRIPTIONS (
  TreatmentID INT NOT NULL,
  PrescriptionID INT NOT NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (TreatmentID, PrescriptionID),
  CONSTRAINT fk_TREATMENTS_has_PRESCRIPTIONS_TREATMENTS1
    FOREIGN KEY (TreatmentID)
    REFERENCES TREATMENTS (TreatmentID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_TREATMENTS_has_PRESCRIPTIONS_PRESCRIPTIONS1
    FOREIGN KEY (PrescriptionID)
    REFERENCES PRESCRIPTIONS (PrescriptionID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX fk_TREATMENTS_has_PRESCRIPTIONS_PRESCRIPTIONS1_idx ON TREATMENTS_PRESCRIPTIONS (PrescriptionID ASC);

CREATE INDEX fk_TREATMENTS_has_PRESCRIPTIONS_TREATMENTS1_idx ON TREATMENTS_PRESCRIPTIONS (TreatmentID ASC);


-- -----------------------------------------------------
-- Table ROLES
-- -----------------------------------------------------
DROP TABLE IF EXISTS ROLES ;

CREATE TABLE IF NOT EXISTS ROLES (
  RoleID INT NOT NULL AUTO_INCREMENT,
  RoleName VARCHAR(15) NOT NULL,
  Description VARCHAR(512) NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedDate DATETIME NULL,
  PRIMARY KEY (RoleID))
ENGINE = InnoDB;

CREATE UNIQUE INDEX RoleName_UNIQUE ON ROLES (RoleName ASC);


-- -----------------------------------------------------
-- Table USERS_ROLES
-- -----------------------------------------------------
DROP TABLE IF EXISTS USERS_ROLES ;

CREATE TABLE IF NOT EXISTS USERS_ROLES (
  UserID INT NOT NULL,
  RoleID INT NOT NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (UserID, RoleID),
  CONSTRAINT fk_ROLES_has_USERS_ROLES1
    FOREIGN KEY (RoleID)
    REFERENCES ROLES (RoleID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_ROLES_has_USERS_USERS1
    FOREIGN KEY (UserID)
    REFERENCES USERS (UserID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX fk_ROLES_has_USERS_USERS1_idx ON USERS_ROLES (UserID ASC);

CREATE INDEX fk_ROLES_has_USERS_ROLES1_idx ON USERS_ROLES (RoleID ASC);


-- -----------------------------------------------------
-- Table PERSON_USERS
-- -----------------------------------------------------
DROP TABLE IF EXISTS PERSON_USERS ;

CREATE TABLE IF NOT EXISTS PERSON_USERS (
  PersonID INT NOT NULL,
  PersonTypeID INT NOT NULL DEFAULT 3,
  UserID INT NOT NULL,
  CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (PersonID, PersonTypeID, UserID),
  CONSTRAINT fk_USERS_has_PERSONS_USERS1
    FOREIGN KEY (UserID)
    REFERENCES USERS (UserID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_PERSON_USERS_PERSONS1
    FOREIGN KEY (PersonID , PersonTypeID)
    REFERENCES PERSONS (PersonID , PersonTypeID)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_USERS_has_PERSONS_USERS1_idx ON PERSON_USERS (UserID ASC);

CREATE INDEX fk_PERSON_USERS_PERSONS1_idx ON PERSON_USERS (PersonID ASC, PersonTypeID ASC);

USE quirondb ;

-- -----------------------------------------------------
-- Placeholder table for view V_USERS_ROLES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS V_USERS_ROLES (Username INT, RoleName INT);

-- -----------------------------------------------------
-- View V_USERS_ROLES
-- -----------------------------------------------------
DROP TABLE IF EXISTS V_USERS_ROLES;
DROP VIEW IF EXISTS V_USERS_ROLES ;
USE quirondb;
CREATE OR REPLACE VIEW V_USERS_ROLES AS
    SELECT
        U.Username AS Username, R.RoleName AS RoleName
    FROM
        USERS_ROLES UR
            INNER JOIN
        USERS U ON UR.UserID = U.UserID
            INNER JOIN
        ROLES R ON UR.RoleID = R.RoleID;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DELETE FROM USERS_ROLES;
DELETE FROM PERSON_USERS;
DELETE FROM TREATMENTS_PRESCRIPTIONS;
DELETE FROM TREATMENTS;
ALTER TABLE TREATMENTS AUTO_INCREMENT = 1;
DELETE FROM PRESCRIPTIONS;
ALTER TABLE PRESCRIPTIONS AUTO_INCREMENT = 1;
DELETE FROM MEDICATIONS;
ALTER TABLE MEDICATIONS AUTO_INCREMENT = 1;
DELETE FROM VISITS;
ALTER TABLE VISITS AUTO_INCREMENT = 1;
DELETE FROM SERVICES;
ALTER TABLE SERVICES AUTO_INCREMENT = 1;
DELETE FROM PROVIDERS_SCHEDULES;
DELETE FROM ENTITY_ADDRESSES;
DELETE FROM SHIFTS_SCHEDULES;
DELETE FROM WEEK_DAYS;
ALTER TABLE WEEK_DAYS AUTO_INCREMENT = 1;
DELETE FROM SHIFTS;
ALTER TABLE SHIFTS AUTO_INCREMENT = 1;
DELETE FROM PATIENTS;
DELETE FROM PROVIDERS;
DELETE FROM PERSONS;
DELETE FROM ORGANIZATIONS;
ALTER TABLE PERSONS AUTO_INCREMENT = 1;
DELETE FROM ENTITIES;
ALTER TABLE ENTITIES AUTO_INCREMENT = 1;
DELETE FROM PERSON_TYPES;
ALTER TABLE PERSON_TYPES AUTO_INCREMENT = 1;
DELETE FROM ADDRESSES;
ALTER TABLE ADDRESSES AUTO_INCREMENT = 1;
DELETE FROM STATE_PROVINCES;
ALTER TABLE STATE_PROVINCES AUTO_INCREMENT = 1;
DELETE FROM COUNTRIES;
ALTER TABLE COUNTRIES AUTO_INCREMENT = 1;
DELETE FROM ADDRESS_TYPES;
ALTER TABLE ADDRESS_TYPES AUTO_INCREMENT = 1;
DELETE FROM USERS;
ALTER TABLE USERS AUTO_INCREMENT = 1;
DELETE FROM ROLES;
ALTER TABLE ROLES AUTO_INCREMENT = 1;
INSERT INTO ROLES (RoleName, Description) VALUES('Administrator', 'System administrator');
INSERT INTO ROLES (RoleName, Description) VALUES('User', 'System user');
INSERT INTO PERSON_TYPES(PersonTypeName) VALUES("Employee");
INSERT INTO PERSON_TYPES(PersonTypeName) VALUES("Provider");
INSERT INTO PERSON_TYPES(PersonTypeName) VALUES("Patient");
INSERT INTO COUNTRIES(CountryCode, Name) VALUES ('US', 'United States');
INSERT INTO COUNTRIES(CountryCode, Name) VALUES ('CO', 'Colombia');
INSERT INTO COUNTRIES(CountryCode, Name) VALUES ('CA', 'Canada');
INSERT INTO COUNTRIES(CountryCode, Name) VALUES ('ES', 'Spain');
INSERT INTO COUNTRIES(CountryCode, Name) VALUES ('FR', 'France');
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('AB','Alberta',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('AK','Alaska',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('AL','Alabama',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('AR','Arkansas',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('AZ','Arizona',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('BC','British Columbia',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('CA','California',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('CO','Colorado',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('CT','Connecticut',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('DC','District of Columbia',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('DE','Delaware',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('FL','Florida',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('GA','Georgia',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('GU','Guam',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('HI','Hawaii',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('IA','Iowa',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('ID','Idaho',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('IL','Illinois',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('IN','Indiana',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('KS','Kansas',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('KY','Kentucky',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('LA','Louisiana',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('LB','Labrador',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('MA','Massachusetts',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('MB','Manitoba',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('MD','Maryland',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('ME','Maine',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('MI','Michigan',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('MN','Minnesota',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('MO','Missouri',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('MS','Mississippi',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('MT','Montana',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('NB','Brunswick',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('NC','North Carolina',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('ND','North Dakota',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('NE','Nebraska',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('NF','Newfoundland',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('NH','New Hampshire',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('NJ','New Jersey',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('NM','New Mexico',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('NS','Nova Scotia',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('NT','Northwest Territories',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('NV','Nevada',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('NY','New York',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('OH','Ohio',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('OK','Oklahoma',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('ON','Ontario',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('OR','Oregon',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('PA','Pennsylvania',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('PE','Prince Edward Island',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('PR','Puerto Rico',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('QC','Quebec',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('RI','Rhode Island',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('SC','South Carolina',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('SD','South Dakota',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('SK','Saskatchewan',3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('TN','Tennessee',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('TX','Texas',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('UT','Utah',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('VA','Virginia',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('VT','Vermont',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('WA','Washington',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('WI','Wisconsin',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('WV','West Virginia',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('WY','Wyoming',1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES('YT','Yukon Territory',3);
INSERT INTO ADDRESS_TYPES(Name) VALUES ('Home');
INSERT INTO ADDRESS_TYPES(Name) VALUES ('Billing');
INSERT INTO ADDRESS_TYPES(Name) VALUES ('Office');
INSERT INTO ADDRESS_TYPES(Name) VALUES ('Shipping');
INSERT INTO ADDRESS_TYPES(Name) VALUES ('Medical Center');
INSERT INTO ORGANIZATION_TYPES(Name) VALUES ('Insurance');
INSERT INTO ORGANIZATION_TYPES(Name) VALUES ('Clinic');
INSERT INTO ORGANIZATION_TYPES(Name) VALUES ('Hospital');
INSERT INTO ENTITIES (CreatedDate) VALUES (CURRENT_TIMESTAMP);
INSERT INTO ORGANIZATIONS(OrganizationID, Name, OrganizationTypeID) VALUE (1, 'Group Health Cooperative', 1);
INSERT INTO ADDRESSES(AddressLine1, AddressLine2, City, StateProvinceID, AddressTypeID, PostalCode, Name) VALUES ('675 W. Washington Ave.', null, 'Madison', 63, 5, 53703, 'Capitol Clinic');
INSERT INTO ENTITY_ADDRESSES(EntityID, AddressID) VALUE (1,1);
INSERT INTO ADDRESSES(AddressLine1, AddressLine2, City, StateProvinceID, AddressTypeID, PostalCode, Name) VALUES ('3051 Cahill Main', null, 'Fitchburg', 63, 5, 53711, 'Hatchery Hill Clinic');
INSERT INTO ENTITY_ADDRESSES(EntityID, AddressID) VALUE (1,2);
INSERT INTO ADDRESSES(AddressLine1, AddressLine2, City, StateProvinceID, AddressTypeID, PostalCode, Name) VALUES ('5249 E. Terrace Dr.', null, 'Madison', 63, 5, 53718, 'East Clinic');
INSERT INTO ENTITY_ADDRESSES(EntityID, AddressID) VALUE (1,3);
INSERT INTO ADDRESSES(AddressLine1, AddressLine2, City, StateProvinceID, AddressTypeID, PostalCode, Name) VALUES ('1705 Hoffman St.', null, 'Madison', 63, 5, 53704, 'Madison College Community Clinic');
INSERT INTO ENTITY_ADDRESSES(EntityID, AddressID) VALUE (1,4);
INSERT INTO ADDRESSES(AddressLine1, AddressLine2, City, StateProvinceID, AddressTypeID, PostalCode, Name) VALUES ('8054 Watts Rd.', null, 'Madison', 63, 5, 53719, 'Princeton Club West PT/OT Clinic');
INSERT INTO ENTITY_ADDRESSES(EntityID, AddressID) VALUE (1,5);
INSERT INTO ADDRESSES(AddressLine1, AddressLine2, City, StateProvinceID, AddressTypeID, PostalCode, Name) VALUES ('8202 Excelsior Dr.', null, 'Madison', 63, 5, 53717, 'Sauk Trails Clinic');
INSERT INTO ENTITY_ADDRESSES(EntityID, AddressID) VALUE (1,6);
INSERT INTO ENTITIES (CreatedDate) VALUES (CURRENT_TIMESTAMP);
INSERT INTO ORGANIZATIONS(OrganizationID, Name, OrganizationTypeID) VALUE (2, 'United Health Care', 1);
INSERT INTO ADDRESSES(AddressLine1, AddressLine2, City, StateProvinceID, AddressTypeID, PostalCode, Name) VALUES ('2135 Silvernail Rd', null, 'Pewaukee', 63, 5, 53072, 'Minuteclinic Walk In Clinic Cvs Pharm');
INSERT INTO ENTITY_ADDRESSES(EntityID, AddressID) VALUE (2,7);
INSERT INTO ADDRESSES(AddressLine1, AddressLine2, City, StateProvinceID, AddressTypeID, PostalCode, Name) VALUES ('221 E Sunset Dr', null, 'Waukesha', 63, 5, 53189, 'Walgreens Healthcare Clinic');
INSERT INTO ENTITY_ADDRESSES(EntityID, AddressID) VALUE (2,8);
INSERT INTO ADDRESSES(AddressLine1, AddressLine2, City, StateProvinceID, AddressTypeID, PostalCode, Name) VALUES ('1305 Randall Rd', null, 'Crystal Lake', 18, 5, 60014, 'Minuteclinic Illinois');
INSERT INTO ENTITY_ADDRESSES(EntityID, AddressID) VALUE (2,9);
INSERT INTO ENTITIES (CreatedDate) VALUES (CURRENT_TIMESTAMP);
INSERT INTO PERSONS (PersonID, PersonTypeID, Title, FirstName, MiddleName, LastName, LastName2, Suffix) VALUES(3, 2, null, 'Yesid', null, 'Perea', 'Martinez', null);
INSERT INTO PROVIDERS(ProviderID, NPI) VALUES(3, '111111');
INSERT INTO ADDRESSES(AddressLine1, AddressLine2, City, StateProvinceID, AddressTypeID, PostalCode) VALUES ('1701 Wright Street', 'Floor 3', 'Madison', 63, 1, 53704);
INSERT INTO ENTITY_ADDRESSES(EntityID, AddressID) VALUE (3,10);
INSERT INTO ENTITIES (CreatedDate) VALUES (CURRENT_TIMESTAMP);
INSERT INTO PERSONS (PersonID, PersonTypeID, Title, FirstName, MiddleName, LastName, LastName2, Suffix) VALUES(4, 2, null, 'Claudia', 'Patricia', 'Carabali', 'Chacon', null);
INSERT INTO PATIENTS(PatientID, BirthDate, Gender, CompanyID, SubscriberCode, IsPrimarySubscriber) VALUES(4, '1974-3-18', 'F', 1, "222222", 1);
INSERT INTO ENTITIES (CreatedDate) VALUES (CURRENT_TIMESTAMP);
INSERT INTO PERSONS (PersonID, PersonTypeID, Title, FirstName, MiddleName, LastName, LastName2, Suffix) VALUES(5, 3, null, 'John', null, 'Smith', null, null);
INSERT INTO PATIENTS(PatientID, BirthDate, Gender, CompanyID, SubscriberCode, IsPrimarySubscriber) VALUES(5, '1966-6-6', 'M', 1, "666666", 1);
INSERT INTO PROVIDERS(ProviderID, NPI) VALUES(4, '111111');
INSERT INTO ADDRESSES(AddressLine1, AddressLine2, City, StateProvinceID, AddressTypeID, PostalCode) VALUES ('3591 Anderson Street', null, 'Madison', 63, 1, 53704);
INSERT INTO ENTITY_ADDRESSES(EntityID, AddressID) VALUE (4,11);
INSERT INTO USERS(Username, Email, Password ) VALUES ('admin', 'admin@aol.com', '1234');
INSERT INTO USERS(Username, Email, Password ) VALUES ('yesper', 'yesper@aol.com', '1234');
INSERT INTO USERS(Username, Email, Password ) VALUES ('clacar', 'clacar@aol.com', '1234');
INSERT INTO USERS(Username, Email, Password ) VALUES ('jsmith', 'jsmith@aol.com', '1234');
INSERT INTO USERS_ROLES(UserID, RoleID) VALUES (1,1);
INSERT INTO USERS_ROLES(UserID, RoleID) VALUES (2,2);
INSERT INTO USERS_ROLES(UserID, RoleID) VALUES (3,2);
INSERT INTO USERS_ROLES(UserID, RoleID) VALUES (4,2);
INSERT INTO PERSON_USERS (PersonID, PersonTypeID, UserID) VALUES (3, 2, 2);
INSERT INTO PERSON_USERS (PersonID, PersonTypeID, UserID) VALUES (4, 2, 3);
INSERT INTO PERSON_USERS (PersonID, PersonTypeID, UserID) VALUES (5, 3, 4);
INSERT INTO SERVICES(Name) VALUES ('Medical');
INSERT INTO SERVICES(Name) VALUES ('Therapy');
INSERT INTO SERVICES(Name) VALUES ('Allergy');
INSERT INTO SERVICES(Name) VALUES ('Psychology');
INSERT INTO SERVICES(Name) VALUES ('Psychiatry');
INSERT INTO WEEK_DAYS(WeekDayCode, Name) VALUES('M', 'Monday');
INSERT INTO WEEK_DAYS(WeekDayCode, Name) VALUES('T', 'Tuesday');
INSERT INTO WEEK_DAYS(WeekDayCode, Name) VALUES('W', 'Wednesday');
INSERT INTO WEEK_DAYS(WeekDayCode, Name) VALUES('R', 'Thursday');
INSERT INTO WEEK_DAYS(WeekDayCode, Name) VALUES('F', 'Friday');
INSERT INTO WEEK_DAYS(WeekDayCode, Name) VALUES('S', 'Saturday');
INSERT INTO WEEK_DAYS(WeekDayCode, Name) VALUES('U', 'Sunday');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekday Morning Spring 2018', 'Weekday Morning Spring 2018', '2018-03-01', '2018-05-31');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekday Afternoon Spring 2018', 'Weekday Afternoon Spring 2018', '2018-03-01', '2018-05-31');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekend Spring 2018', 'Weekend Spring 2018', '2018-03-01', '2018-05-31');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekday Morning Summer 2018', 'Weekday Morning Summer 2018', '2018-06-01', '2018-08-31');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekday Afternoon Summer 2018', 'Weekday Afternoon Summer 2018', '2018-06-01', '2018-08-31');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekend Summer 2018', 'Weekend Summer 2018', '2018-06-01', '2018-08-31');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekday Morning Fall 2018', 'Weekday Morning Fall 2018', '2018-09-01', '2018-11-30');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekday Afternoon Fall 2018', 'Weekday Afternoon Fall 2018', '2018-09-01', '2018-11-30');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekend Fall 2018', 'Weekend Fall 2018', '2018-09-01', '2018-11-30');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekday Morning Winter 2018', 'Weekday Morning Winter 2018', '2018-12-01', '2019-02-28');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekday Afternoon Winter 2018', 'Weekday Afternoon Winter 2018', '2018-12-01', '2019-02-28');
INSERT INTO SHIFTS(Name, Description, StartDate, EndDate) VALUES('Weekend Winter 2018', 'Weekend Winter 2018', '2018-12-01', '2019-02-28');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (1, 1, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (1, 2, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (1, 3, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (1, 4, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (1, 5, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (2, 1, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (2, 2, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (2, 3, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (2, 4, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (2, 5, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (3, 6, '09:00', '13:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (4, 1, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (4, 2, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (4, 3, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (4, 4, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (4, 5, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (5, 1, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (5, 2, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (5, 3, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (5, 4, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (5, 5, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (6, 6, '09:00', '13:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (7, 1, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (7, 2, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (7, 3, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (7, 4, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (7, 5, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (8, 1, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (8, 2, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (8, 3, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (8, 4, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (8, 5, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (9, 6, '09:00', '13:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (10, 1, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (10, 2, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (10, 3, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (10, 4, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (10, 5, '08:00', '12:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (11, 1, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (11, 2, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (11, 3, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (11, 4, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (11, 5, '13:00', '18:00');
INSERT INTO SHIFTS_SCHEDULES(ShiftID, WeekDayID, StartTime, EndTime) VALUES (12, 6, '09:00', '13:00');
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 1, 1, 1, 1);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 2, 2, 1, 2);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 2, 3, 1, 3);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 2, 4, 1, 4);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 1, 5, 1, 5);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 3, 6, 1, 6);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 4, 1, 1, 1);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 5, 2, 1, 2);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 5, 3, 1, 3);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 5, 4, 1, 4);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 4, 5, 1, 5);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 6, 6, 1, 6);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 7, 1, 1, 1);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 8, 2, 1, 2);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 8, 3, 1, 3);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 8, 4, 1, 4);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 7, 5, 1, 5);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 9, 6, 1, 6);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 10, 1, 1, 1);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 11, 2, 1, 2);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 11, 3, 1, 3);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 11, 4, 1, 4);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 10, 5, 1, 5);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (3, 12, 6, 1, 6);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 1, 1, 2, 7);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 2, 2, 2, 7);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 2, 3, 2, 8);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 2, 4, 2, 9);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 1, 5, 2, 7);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 4, 1, 2, 7);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 5, 2, 2, 7);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 5, 3, 2, 8);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 5, 4, 2, 9);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 4, 5, 2, 7);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 7, 1, 2, 7);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 8, 2, 2, 7);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 8, 3, 2, 8);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 8, 4, 2, 9);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 7, 5, 2, 7);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 10, 1, 2, 7);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 11, 2, 2, 7);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 11, 3, 2, 8);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 11, 4, 2, 9);
INSERT INTO PROVIDERS_SCHEDULES(ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID) VALUES (4, 10, 5, 2, 7);
INSERT INTO VISITS(PatientID, ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID, ServiceID, Status, ScheduledStartDate, ScheduledEndDate, SymptomID, SymptomName, DiagnosticID, DiagnosticName, ActualStartDate, ActualEndDate, PatientBloodPressure, PatientWeight, PatientTemperature, PatientRespiration, PatientBMI, PatientHeight, PatientPulse, PatientSymptoms, ProviderComments) VALUES(5, 3, 2, 3, 1, 3, 2, 'D', '2018-01-10 14:30', '2018-01-10 14:30', 10, 'Headache', 1, 'Diagnostic 1', '2018-01-10 14:00', '2018-01-10 14:30', 125, 125, 98.3, 16, 26.92, 4.5, 85, 'Sore throat', 'Patient has flu');
INSERT INTO VISITS(PatientID, ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID, ServiceID, Status, ScheduledStartDate, ScheduledEndDate, SymptomID, SymptomName, DiagnosticID, DiagnosticName, ActualStartDate, ActualEndDate, PatientBloodPressure, PatientWeight, PatientTemperature, PatientRespiration, PatientBMI, PatientHeight, PatientPulse, PatientSymptoms, ProviderComments) VALUES(5, 3, 2, 3, 1, 3, 2, 'C', '2018-01-17 14:00', '2018-01-17 14:30', 10, 'Headache', 1, 'Diagnostic 1', '2018-01-17 14:00', '2018-01-17 14:30', 125, 125, 98.3, 16, 26.92, 4.5, 85, 'Sore throat', 'Patient has flu');
INSERT INTO VISITS(PatientID, ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID, ServiceID, Status, ScheduledStartDate, ScheduledEndDate, ActualStartDate, ActualEndDate, PatientBloodPressure, PatientWeight, PatientTemperature, PatientRespiration, PatientBMI, PatientHeight, PatientPulse, PatientSymptoms, ProviderComments) VALUES(5, 4, 2, 2, 2, 7, 1, 'D', '2018-02-13 13:00', '2018-02-13 13:30', '2018-02-13 13:00', '2018-02-13 13:30', 126, 126, 96.3, 15, 25.92, 4.5, 85, 'Headache', 'Patient has migraine');
INSERT INTO VISITS(PatientID, ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID, ServiceID, Status, ScheduledStartDate, ScheduledEndDate, ActualStartDate, ActualEndDate, PatientBloodPressure, PatientWeight, PatientTemperature, PatientRespiration, PatientBMI, PatientHeight, PatientPulse, PatientSymptoms, ProviderComments) VALUES(5, 4, 2, 2, 2, 7, 1, 'C', '2018-02-20 14:00', '2018-02-20 14:30', '2018-02-20 14:00', '2018-02-20 14:30', 126, 126, 96.3, 15, 25.92, 4.5, 85, 'Headache', 'Patient has migraine');
INSERT INTO VISITS(PatientID, ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID, ServiceID, Status, ScheduledStartDate, ScheduledEndDate, ActualStartDate, ActualEndDate, PatientBloodPressure, PatientWeight, PatientTemperature, PatientRespiration, PatientBMI, PatientHeight, PatientPulse, PatientSymptoms, ProviderComments) VALUES(5, 4, 2, 2, 2, 7, 1, 'C', '2018-02-27 14:00', '2018-02-27 14:30', '2018-02-27 14:00', '2018-02-27 14:30', 126, 126, 96.3, 15, 25.92, 4.5, 85, 'Sore throat', 'Patient has flu');
INSERT INTO VISITS(PatientID, ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID, ServiceID, Status, ScheduledStartDate, ScheduledEndDate, ActualStartDate, ActualEndDate, PatientBloodPressure, PatientWeight, PatientTemperature, PatientRespiration, PatientBMI, PatientHeight, PatientPulse, PatientSymptoms, ProviderComments) VALUES(5, 3, 5, 4, 1, 4, 1, 'C','2018-07-18 16:00', '2018-07-18 16:30', '2018-07-18 16:00', '2018-07-18 16:15',120, 120, 97.3, 16, 25.92, 4.5, 82,'Ear pain', 'Patient has an infection in the ear canal');
INSERT INTO VISITS(PatientID, ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID, ServiceID, Status, ScheduledStartDate, ScheduledEndDate, PatientSymptoms) VALUES(5, 3, 11, 3, 1, 3, 2, 'A', '2018-11-14 16:00', '2018-11-14 16:30', 'Knee pain');
INSERT INTO VISITS(PatientID, ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID, ServiceID, Status, ScheduledStartDate, ScheduledEndDate, PatientSymptoms) VALUES(5, 4, 10, 1, 2, 7, 2, 'A', '2018-12-10 9:00', '2018-12-14 9:30', 'Shoulder pain');
INSERT INTO VISITS(PatientID, ProviderID, ShiftID, WeekDayID, OrganizationID, LocationID, ServiceID, Status, ScheduledStartDate, ScheduledEndDate, PatientSymptoms) VALUES(5, 4, 10, 5, 2, 7, 2, 'A', '2018-12-21 10:00', '2018-12-21 10:30', 'Knee pain');
INSERT INTO TREATMENTS(VisitID, StartDate, EndDate, PatientComments, ProviderComments, Status, Evaluation)VALUES(1, '2018-01-01', '2018-02-01', 'I feel better now', 'Follow treatment', 'C', 4.5);
INSERT INTO TREATMENTS(VisitID, StartDate, EndDate, PatientComments, ProviderComments, Status, Evaluation)VALUES(2, '2018-01-01', '2018-02-01', 'I feel better now', 'Follow treatment', 'C', 4.5);
INSERT INTO MEDICATIONS(Name, CommonName, Description, GeneralInstructions)VALUES('Robitussin', 'Robitussin', 'Power through your day with an enhanced formula that soothes your irritated throat and provides fast and powerful relief from your worst cough, cold & flu symptoms.', '10 mL every 12 hours, not to exceed 20 mL in 24 hours.');
INSERT INTO MEDICATIONS(Name, CommonName, Description, GeneralInstructions)VALUES('Ibuprofen', 'Advil+', 'Ibuprofen is a medication in the nonsteroidal anti-inflammatory drug class that is used for treating pain, fever, and inflammation.', '800 milligrams per dose or 3200 mg per day.');
INSERT INTO PRESCRIPTIONS(MedicationID, Instructions) VALUES (1, '10 mL every 12 hours, not to exceed 20 mL in 24 hours.');
INSERT INTO PRESCRIPTIONS(MedicationID, Instructions) VALUES (2, '100 mg every 12 hours, not to exceed 200 mg in 24 hours.');
INSERT INTO TREATMENTS_PRESCRIPTIONS(TreatmentID, PrescriptionID) VALUES (1,1);
INSERT INTO TREATMENTS_PRESCRIPTIONS(TreatmentID, PrescriptionID) VALUES (2,2);

EOF