DELETE FROM STATE_PROVINCES;
ALTER TABLE STATE_PROVINCES AUTO_INCREMENT = 1;
DELETE FROM COUNTRIES;
ALTER TABLE COUNTRIES AUTO_INCREMENT = 1;
DELETE FROM ADDRESS_TYPES;
ALTER TABLE ADDRESS_TYPES AUTO_INCREMENT = 1;
DELETE FROM USERS;
ALTER TABLE USERS AUTO_INCREMENT = 1;
DELETE FROM ROLES;
ALTER TABLE ROLES AUTO_INCREMENT = 1;
INSERT INTO ROLES (RoleName, Description) VALUES('Administrator', 'System administrator');
INSERT INTO ROLES (RoleName, Description) VALUES('User', 'System user');
INSERT INTO USERS(Username, Email, Password ) VALUES ('yesper', 'yesper@aol.com', '1234');
INSERT INTO USERS(Username, Email, Password ) VALUES ('clacar', 'clacar@aol.com', '4567');
INSERT INTO COUNTRIES(CountryCode, Name) VALUES ('US', 'United States');
INSERT INTO COUNTRIES(CountryCode, Name) VALUES ('CO', 'Colombia');
INSERT INTO COUNTRIES(CountryCode, Name) VALUES ('CA', 'Canada');
INSERT INTO COUNTRIES(CountryCode, Name) VALUES ('ES', 'Spain');
INSERT INTO COUNTRIES(CountryCode, Name) VALUES ('FR', 'France');
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES ('AK', 'Alaska', 1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES ('AL', 'Alabama', 1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES ('AR', 'Arkansas', 1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES ('AZ', 'Arizona', 1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES ('CA', 'California', 1);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES ('AB', 'Alberta', 3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES ('BC', 'British Columbia', 3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES ('LB', 'Labrador', 3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES ('MB', 'Manitoba', 3);
INSERT INTO STATE_PROVINCES (StateProvinceCode, Name, CountryID) VALUES ('NB', 'Brunswick', 3);
INSERT INTO ADDRESS_TYPES(Name) VALUES ('Home');
INSERT INTO ADDRESS_TYPES(Name) VALUES ('Billing');
INSERT INTO ADDRESS_TYPES(Name) VALUES ('Office');
INSERT INTO ADDRESS_TYPES(Name) VALUES ('Primary');
INSERT INTO ADDRESS_TYPES(Name) VALUES ('Shipping');